version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
    - "node.name=es-node"
    - "discovery.type=single-node"
    - "cluster.name=app-search-docker-cluster"
    - "bootstrap.memory_lock=true"
    - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data

  appsearch:
    image: docker.elastic.co/app-search/app-search:7.6.0
    environment:
    - "elasticsearch.host=http://elasticsearch:9200"
    - "allow_es_settings_modification=true"
    - "JAVA_OPTS=-Xms2g -Xmx4g"
    ports:
      - 3002:3002

  broker:
    image: rabbitmq:3.8.2
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: wh4tsth3d34l
      RABBITMQ_DEFAULT_VHOST: celery

  worker:
    build: .
    command: usb tasks.worker
    environment:
      - APPSEARCH_PRIVATE_KEY
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
    volumes:
      - $VIDEOS_FOLDER:/videos:ro
      - thumbs:/thumbnails

  result:
    image: redis:5.0
    command: redis-server --appendonly yes
    volumes:
      - results:/data

  web:
    build: .
    command: usb server.run
    environment:
      - APPSEARCH_PRIVATE_KEY
      - FLASK_APP=usb.server
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
    volumes:
      - thumbs:/thumbnails:ro
    ports:
      - 5000:5000

  flower:
    build: .
    command: usb tasks.flower
    ports:
      - 5555:5555

  bot:
    build: .
    command: usb discord.run
    stop_grace_period: 15s
    environment:
      - DISCORD_TOKEN
      - APPSEARCH_PRIVATE_KEY
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
    volumes:
      - thumbs:/thumbnails:ro

volumes:
  es:
    driver: local
  thumbs:
    driver: local
  results:
    driver: local
