version: '2'

services:
  meilisearch:
    image: getmeili/meilisearch:v0.18.1
    volumes:
      - ms:/var/lib/ms
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY
      - MEILI_API_KEY_PRIVATE
      - MEILI_DB_PATH=/var/lib/ms
      - MEILI_NO_ANALYTICS=true

  broker:
    image: rabbitmq:3.8.11
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: wh4tsth3d34l
      RABBITMQ_DEFAULT_VHOST: celery

  worker:
    build: .
    command: celery -A usb.tasks worker
    environment:
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
      - MEILI_API_KEY_PRIVATE
    volumes:
      - $VIDEOS_FOLDER:/videos:ro
      - thumbs:/thumbnails

  result:
    image: redis:6.0.10
    command: redis-server --appendonly yes
    volumes:
      - results:/data

  web:
    build: .
    command: usb server.run
    environment:
      - FLASK_APP=usb.server
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
      - MEILI_API_KEY_PRIVATE
    volumes:
      - thumbs:/thumbnails:ro
    ports:
      - 5000:5000

  flower:
    build: .
    command: celery -A usb.tasks flower --port=5555
    ports:
      - 5555:5555

  bot:
    build: .
    command: usb discord.run
    stop_grace_period: 15s
    environment:
      - DISCORD_TOKEN
      - DBL_TOKEN
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - BASE_URL
      - MEILI_API_KEY_PRIVATE
      - PING_URL
    volumes:
      - thumbs:/thumbnails:ro

volumes:
  thumbs:
    driver: local
  results:
    driver: local
  ms:
    driver: local
