apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: usb-es
  name: usb-es
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: usb-es
  storageClassName: ""
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-es
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/snap/microk8s/common/default-storage/usb-es
