apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  labels:
    io.kompose.service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: bot
    spec:
      containers:
        - image: usb
          args: ["python3", "-m", "usb.bot"]
          env:
            - name: APPSEARCH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: appsearch
                  key: private_key
            - name: PYTHONASYNCIODEBUG
              value: "1"
            - name: SERVICE_NAME_BROKER
              value: $(SERVICE_NAME_BROKER)
            - name: SERVICE_NAME_RESULT
              value: $(SERVICE_NAME_RESULT)
            - name: SERVICE_NAME_APPSEARCH
              value: $(SERVICE_NAME_APPSEARCH)
            - name: LOGURU_LEVEL
              value: DEBUG
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-token
                  key: DISCORD_TOKEN
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn

          name: bot
          volumeMounts:
            - mountPath: /thumbnails
              name: thumbnails
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: thumbnails
          persistentVolumeClaim:
            claimName: thumbnails
            readOnly: true
