apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
      - name: any
        env:
          - name: SERVICE_NAME_BROKER
            value: $(SERVICE_NAME_BROKER)
          - name: SERVICE_NAME_RESULT
            value: $(SERVICE_NAME_RESULT)
